// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH-IJ2onETPHx6qaBmf5H6WnymIg7vdwE',
    appId: '1:978313264687:web:de485da84f3c8982fd10da',
    messagingSenderId: '978313264687',
    projectId: 'doctpoint-7ab12',
    authDomain: 'doctpoint-7ab12.firebaseapp.com',
    databaseURL: 'https://doctpoint-7ab12-default-rtdb.firebaseio.com',
    storageBucket: 'doctpoint-7ab12.firebasestorage.app',
    measurementId: 'G-WF90TJCQVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6WIKsv8WkHcfMkzy-wTQbyStpQZV6-FE',
    appId: '1:978313264687:android:f5b5109d2147d51cfd10da',
    messagingSenderId: '978313264687',
    projectId: 'doctpoint-7ab12',
    databaseURL: 'https://doctpoint-7ab12-default-rtdb.firebaseio.com',
    storageBucket: 'doctpoint-7ab12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEHOTrUPghDpeFyNhSvfJIDS_pm5cgpBU',
    appId: '1:978313264687:ios:37ae1c63f9d590b3fd10da',
    messagingSenderId: '978313264687',
    projectId: 'doctpoint-7ab12',
    databaseURL: 'https://doctpoint-7ab12-default-rtdb.firebaseio.com',
    storageBucket: 'doctpoint-7ab12.firebasestorage.app',
    iosBundleId: 'com.example.axionkey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEHOTrUPghDpeFyNhSvfJIDS_pm5cgpBU',
    appId: '1:978313264687:ios:37ae1c63f9d590b3fd10da',
    messagingSenderId: '978313264687',
    projectId: 'doctpoint-7ab12',
    databaseURL: 'https://doctpoint-7ab12-default-rtdb.firebaseio.com',
    storageBucket: 'doctpoint-7ab12.firebasestorage.app',
    iosBundleId: 'com.example.axionkey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH-IJ2onETPHx6qaBmf5H6WnymIg7vdwE',
    appId: '1:978313264687:web:b0ca1b388ad74fe7fd10da',
    messagingSenderId: '978313264687',
    projectId: 'doctpoint-7ab12',
    authDomain: 'doctpoint-7ab12.firebaseapp.com',
    databaseURL: 'https://doctpoint-7ab12-default-rtdb.firebaseio.com',
    storageBucket: 'doctpoint-7ab12.firebasestorage.app',
    measurementId: 'G-2GFHPYG9R7',
  );
}
